# Generated by Django 4.2.3 on 2023-08-16 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('total_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('issued_quantity', models.IntegerField(default=0)),
                ('recieved_quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount_recieved', models.IntegerField(default=0)),
                ('issued_to', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField(default=0)),
                ('branch_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.product')),
            ],
        ),
    ]
