# Generated by Django 4.2.3 on 2023-07-31 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('total_quatity', models.IntegerField(default=0)),
                ('issued_quatity', models.IntegerField(default=0)),
                ('recieved_quatity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApplication.category')),
            ],
        ),
    ]
