# Generated by Django 4.2.3 on 2023-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='received_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
