# Generated by Django 4.2.3 on 2023-08-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0002_product_part_number_product_received_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
    ]
