# Generated by Django 4.2.3 on 2023-08-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0003_rename_sales_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recieved_quatity',
            new_name='recieved_quantity',
        ),
    ]
