# Generated by Django 4.2.3 on 2023-08-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0004_rename_recieved_quatity_product_recieved_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='issued_quatity',
            new_name='issued_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='total_quatity',
            new_name='total_quantity',
        ),
    ]
