# Generated by Django 4.2.3 on 2023-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0007_alter_product_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_recieved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
