# Generated by Django 4.2.3 on 2023-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0009_alter_product_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recieved_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
