# Generated by Django 4.2.3 on 2023-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0010_alter_product_recieved_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recieved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
