# Generated by Django 4.2.3 on 2023-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApplication', '0013_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
